added CDDTOKEN to CI

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -47,12 +47,14 @@ jobs:
 
     # More info on options: https://github.com/mamba-org/provision-with-micromamba
     - name: Setup Conda Environment
-      uses: mamba-org/provision-with-micromamba@main
+      uses: mamba-org/setup-micromamba@v1
       with:
         environment-file: devtools/conda-envs/asapdiscovery.yaml
         environment-name: asapdiscovery
         channels: jaimergp/label/unsupported-cudatoolkit-shim,conda-forge,openeye,dglteam
-        extra-specs: |
+        cache-env: true
+        cache-downloads: true
+        create-args: >-
           python==${{ matrix.python-version }}
 
     - name: Test OE License & Write License to File
@@ -64,22 +66,21 @@ jobs:
 
     - name: Install packages
       run: |
-        python -m pip install ./asapdiscovery-data --no-deps
-        python -m pip install ./asapdiscovery-dataviz --no-deps
-        python -m pip install ./asapdiscovery-docking --no-deps
-        python -m pip install ./asapdiscovery-ml --no-deps
+        python -m pip install -e ./asapdiscovery-data --no-deps
+        python -m pip install -e ./asapdiscovery-dataviz --no-deps
+        python -m pip install -e ./asapdiscovery-docking --no-deps
+        python -m pip install -e ./asapdiscovery-ml --no-deps
+        python -m pip install -e ./asapdiscovery-modeling --no-deps
         micromamba list
 
-
     - name: Run tests
+      env:
+        CDDTOKEN: ${{ secrets.ASAP_CDD_VAULT_TOKEN_READ_ONLY }}
       run: |
         # run each package test suite; append to coverage file
-        coverage run --append --source=./asapdiscovery-data/asapdiscovery/data/ -m pytest -v  --color=yes ./asapdiscovery-data/asapdiscovery/data/tests/
-        coverage run --append --source=./asapdiscovery-dataviz/asapdiscovery/dataviz/ -m pytest -v  --color=yes ./asapdiscovery-dataviz/asapdiscovery/dataviz/tests/
-        coverage run --append --source=./asapdiscovery-docking/asapdiscovery/docking/ -m pytest -v  --color=yes ./asapdiscovery-docking/asapdiscovery/docking/tests/
-        coverage run --append --source=./asapdiscovery-ml/asapdiscovery/ml/ -m pytest -v  --color=yes ./asapdiscovery-ml/asapdiscovery/ml/tests/
-        # generate xml report from .coverage file
-        coverage xml
+        # Exit immediately if a command exits with a non-zero status.
+        set -e
+        pytest -n auto --durations=10 --cov=asapdiscovery-modeling --cov=asapdiscovery-data --cov=asapdiscovery-dataviz --cov=asapdiscovery-docking --cov=asapdiscovery-ml -v --cov-report=xml --cov-report=term --color=yes asapdiscovery-data/asapdiscovery/data/tests asapdiscovery-dataviz/asapdiscovery/dataviz/tests asapdiscovery-modeling/asapdiscovery/modeling/tests asapdiscovery-docking/asapdiscovery/docking/tests asapdiscovery-ml/asapdiscovery/ml/tests
 
     - name: Upload Code Coverage to Codecov
       uses: codecov/codecov-action@v3
@@ -90,4 +91,4 @@ jobs:
         file: ./coverage.xml
         flags: unittests
         name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
-        fail_ci_if_error: true
+        fail_ci_if_error: false
